/**
 * generated by Xtext 2.11.0
 */
package uk.ac.kcl.mde.rinform.validation;

import uk.ac.kcl.mde.rinform.validation.AbstractRInformValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RInformValidator extends AbstractRInformValidator {
}
