/*
 * generated by Xtext 2.11.0
 */
package uk.ac.kcl.mde.rinform.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.mde.rinform.parser.antlr.internal.InternalRInformParser;
import uk.ac.kcl.mde.rinform.services.RInformGrammarAccess;

public class RInformParser extends AbstractAntlrParser {

	@Inject
	private RInformGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRInformParser createParser(XtextTokenStream stream) {
		return new InternalRInformParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RInformGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RInformGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
