/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.rinform;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Container Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.mde.rinform.RinformPackage#getContainerDeclaration()
 * @model
 * @generated
 */
public interface ContainerDeclaration extends ItemDeclaration
{
} // ContainerDeclaration
