/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.rinform;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Person Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mde.rinform.PersonDescription#getPersonDescription <em>Person Description</em>}</li>
 *   <li>{@link uk.ac.kcl.mde.rinform.PersonDescription#getPerson <em>Person</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mde.rinform.RinformPackage#getPersonDescription()
 * @model
 * @generated
 */
public interface PersonDescription extends SentencePart
{
  /**
   * Returns the value of the '<em><b>Person Description</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person Description</em>' attribute list.
   * @see uk.ac.kcl.mde.rinform.RinformPackage#getPersonDescription_PersonDescription()
   * @model unique="false"
   * @generated
   */
  EList<String> getPersonDescription();

  /**
   * Returns the value of the '<em><b>Person</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person</em>' reference.
   * @see #setPerson(PersonDeclaration)
   * @see uk.ac.kcl.mde.rinform.RinformPackage#getPersonDescription_Person()
   * @model
   * @generated
   */
  PersonDeclaration getPerson();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mde.rinform.PersonDescription#getPerson <em>Person</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Person</em>' reference.
   * @see #getPerson()
   * @generated
   */
  void setPerson(PersonDeclaration value);

} // PersonDescription
