/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.rinform;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reverse Inform Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mde.rinform.ReverseInformProgram#getSentences <em>Sentences</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mde.rinform.RinformPackage#getReverseInformProgram()
 * @model
 * @generated
 */
public interface ReverseInformProgram extends EObject
{
  /**
   * Returns the value of the '<em><b>Sentences</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.mde.rinform.SentencePart}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sentences</em>' containment reference list.
   * @see uk.ac.kcl.mde.rinform.RinformPackage#getReverseInformProgram_Sentences()
   * @model containment="true"
   * @generated
   */
  EList<SentencePart> getSentences();

} // ReverseInformProgram
