/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.rinform;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.mde.rinform.RinformFactory
 * @model kind="package"
 * @generated
 */
public interface RinformPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rinform";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/mde/Rinform";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rinform";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RinformPackage eINSTANCE = uk.ac.kcl.mde.rinform.impl.RinformPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.ReverseInformProgramImpl <em>Reverse Inform Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.ReverseInformProgramImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getReverseInformProgram()
   * @generated
   */
  int REVERSE_INFORM_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Sentences</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVERSE_INFORM_PROGRAM__SENTENCES = 0;

  /**
   * The number of structural features of the '<em>Reverse Inform Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVERSE_INFORM_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.SentencePartImpl <em>Sentence Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.SentencePartImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getSentencePart()
   * @generated
   */
  int SENTENCE_PART = 1;

  /**
   * The number of structural features of the '<em>Sentence Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE_PART_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.RoomDeclarationImpl <em>Room Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.RoomDeclarationImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getRoomDeclaration()
   * @generated
   */
  int ROOM_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_DECLARATION__NAME = SENTENCE_PART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Room Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_DECLARATION_FEATURE_COUNT = SENTENCE_PART_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.RoomAliasImpl <em>Room Alias</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.RoomAliasImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getRoomAlias()
   * @generated
   */
  int ROOM_ALIAS = 3;

  /**
   * The feature id for the '<em><b>Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_ALIAS__ROOM = SENTENCE_PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Aliases</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_ALIAS__ALIASES = SENTENCE_PART_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Room Alias</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_ALIAS_FEATURE_COUNT = SENTENCE_PART_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.RoomDescriptionImpl <em>Room Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.RoomDescriptionImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getRoomDescription()
   * @generated
   */
  int ROOM_DESCRIPTION = 4;

  /**
   * The feature id for the '<em><b>Room Description</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_DESCRIPTION__ROOM_DESCRIPTION = SENTENCE_PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_DESCRIPTION__ROOM = SENTENCE_PART_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Room Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_DESCRIPTION_FEATURE_COUNT = SENTENCE_PART_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.ItemDeclarationImpl <em>Item Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.ItemDeclarationImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getItemDeclaration()
   * @generated
   */
  int ITEM_DECLARATION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_DECLARATION__NAME = SENTENCE_PART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Item Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_DECLARATION_FEATURE_COUNT = SENTENCE_PART_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.ContainerDeclarationImpl <em>Container Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.ContainerDeclarationImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getContainerDeclaration()
   * @generated
   */
  int CONTAINER_DECLARATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_DECLARATION__NAME = ITEM_DECLARATION__NAME;

  /**
   * The feature id for the '<em><b>Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_DECLARATION__ROOM = ITEM_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Container Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_DECLARATION_FEATURE_COUNT = ITEM_DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.ItemInRoomDeclarationImpl <em>Item In Room Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.ItemInRoomDeclarationImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getItemInRoomDeclaration()
   * @generated
   */
  int ITEM_IN_ROOM_DECLARATION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_IN_ROOM_DECLARATION__NAME = ITEM_DECLARATION__NAME;

  /**
   * The feature id for the '<em><b>Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_IN_ROOM_DECLARATION__ROOM = ITEM_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Item In Room Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_IN_ROOM_DECLARATION_FEATURE_COUNT = ITEM_DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.ItemInContainerDeclarationImpl <em>Item In Container Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.ItemInContainerDeclarationImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getItemInContainerDeclaration()
   * @generated
   */
  int ITEM_IN_CONTAINER_DECLARATION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_IN_CONTAINER_DECLARATION__NAME = ITEM_DECLARATION__NAME;

  /**
   * The feature id for the '<em><b>Container</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_IN_CONTAINER_DECLARATION__CONTAINER = ITEM_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Item In Container Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_IN_CONTAINER_DECLARATION_FEATURE_COUNT = ITEM_DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.ItemDescriptionImpl <em>Item Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.ItemDescriptionImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getItemDescription()
   * @generated
   */
  int ITEM_DESCRIPTION = 9;

  /**
   * The feature id for the '<em><b>Item Description</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_DESCRIPTION__ITEM_DESCRIPTION = SENTENCE_PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_DESCRIPTION__ITEM = SENTENCE_PART_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Item Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_DESCRIPTION_FEATURE_COUNT = SENTENCE_PART_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.CharacterDeclarationImpl <em>Character Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.CharacterDeclarationImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getCharacterDeclaration()
   * @generated
   */
  int CHARACTER_DECLARATION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_DECLARATION__NAME = SENTENCE_PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_DECLARATION__ROOM = SENTENCE_PART_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Character Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_DECLARATION_FEATURE_COUNT = SENTENCE_PART_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.CharacterDescriptionImpl <em>Character Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.CharacterDescriptionImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getCharacterDescription()
   * @generated
   */
  int CHARACTER_DESCRIPTION = 11;

  /**
   * The feature id for the '<em><b>Person Description</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_DESCRIPTION__PERSON_DESCRIPTION = SENTENCE_PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Person</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_DESCRIPTION__PERSON = SENTENCE_PART_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Character Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_DESCRIPTION_FEATURE_COUNT = SENTENCE_PART_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.DirectionStatementImpl <em>Direction Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.DirectionStatementImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getDirectionStatement()
   * @generated
   */
  int DIRECTION_STATEMENT = 12;

  /**
   * The feature id for the '<em><b>Room1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTION_STATEMENT__ROOM1 = SENTENCE_PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTION_STATEMENT__DIRECTION = SENTENCE_PART_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Room2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTION_STATEMENT__ROOM2 = SENTENCE_PART_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Direction Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTION_STATEMENT_FEATURE_COUNT = SENTENCE_PART_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.impl.WordsImpl <em>Words</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.impl.WordsImpl
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getWords()
   * @generated
   */
  int WORDS = 13;

  /**
   * The feature id for the '<em><b>Words</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORDS__WORDS = SENTENCE_PART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Words</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORDS_FEATURE_COUNT = SENTENCE_PART_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.mde.rinform.Direction <em>Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.mde.rinform.Direction
   * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getDirection()
   * @generated
   */
  int DIRECTION = 14;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.ReverseInformProgram <em>Reverse Inform Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reverse Inform Program</em>'.
   * @see uk.ac.kcl.mde.rinform.ReverseInformProgram
   * @generated
   */
  EClass getReverseInformProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.mde.rinform.ReverseInformProgram#getSentences <em>Sentences</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sentences</em>'.
   * @see uk.ac.kcl.mde.rinform.ReverseInformProgram#getSentences()
   * @see #getReverseInformProgram()
   * @generated
   */
  EReference getReverseInformProgram_Sentences();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.SentencePart <em>Sentence Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sentence Part</em>'.
   * @see uk.ac.kcl.mde.rinform.SentencePart
   * @generated
   */
  EClass getSentencePart();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.RoomDeclaration <em>Room Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room Declaration</em>'.
   * @see uk.ac.kcl.mde.rinform.RoomDeclaration
   * @generated
   */
  EClass getRoomDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.mde.rinform.RoomDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.mde.rinform.RoomDeclaration#getName()
   * @see #getRoomDeclaration()
   * @generated
   */
  EAttribute getRoomDeclaration_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.RoomAlias <em>Room Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room Alias</em>'.
   * @see uk.ac.kcl.mde.rinform.RoomAlias
   * @generated
   */
  EClass getRoomAlias();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.RoomAlias#getRoom <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Room</em>'.
   * @see uk.ac.kcl.mde.rinform.RoomAlias#getRoom()
   * @see #getRoomAlias()
   * @generated
   */
  EReference getRoomAlias_Room();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.mde.rinform.RoomAlias#getAliases <em>Aliases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Aliases</em>'.
   * @see uk.ac.kcl.mde.rinform.RoomAlias#getAliases()
   * @see #getRoomAlias()
   * @generated
   */
  EAttribute getRoomAlias_Aliases();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.RoomDescription <em>Room Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room Description</em>'.
   * @see uk.ac.kcl.mde.rinform.RoomDescription
   * @generated
   */
  EClass getRoomDescription();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.mde.rinform.RoomDescription#getRoomDescription <em>Room Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Room Description</em>'.
   * @see uk.ac.kcl.mde.rinform.RoomDescription#getRoomDescription()
   * @see #getRoomDescription()
   * @generated
   */
  EAttribute getRoomDescription_RoomDescription();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.RoomDescription#getRoom <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Room</em>'.
   * @see uk.ac.kcl.mde.rinform.RoomDescription#getRoom()
   * @see #getRoomDescription()
   * @generated
   */
  EReference getRoomDescription_Room();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.ContainerDeclaration <em>Container Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container Declaration</em>'.
   * @see uk.ac.kcl.mde.rinform.ContainerDeclaration
   * @generated
   */
  EClass getContainerDeclaration();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.ContainerDeclaration#getRoom <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Room</em>'.
   * @see uk.ac.kcl.mde.rinform.ContainerDeclaration#getRoom()
   * @see #getContainerDeclaration()
   * @generated
   */
  EReference getContainerDeclaration_Room();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.ItemInRoomDeclaration <em>Item In Room Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item In Room Declaration</em>'.
   * @see uk.ac.kcl.mde.rinform.ItemInRoomDeclaration
   * @generated
   */
  EClass getItemInRoomDeclaration();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.ItemInRoomDeclaration#getRoom <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Room</em>'.
   * @see uk.ac.kcl.mde.rinform.ItemInRoomDeclaration#getRoom()
   * @see #getItemInRoomDeclaration()
   * @generated
   */
  EReference getItemInRoomDeclaration_Room();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.ItemInContainerDeclaration <em>Item In Container Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item In Container Declaration</em>'.
   * @see uk.ac.kcl.mde.rinform.ItemInContainerDeclaration
   * @generated
   */
  EClass getItemInContainerDeclaration();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.ItemInContainerDeclaration#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Container</em>'.
   * @see uk.ac.kcl.mde.rinform.ItemInContainerDeclaration#getContainer()
   * @see #getItemInContainerDeclaration()
   * @generated
   */
  EReference getItemInContainerDeclaration_Container();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.ItemDeclaration <em>Item Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item Declaration</em>'.
   * @see uk.ac.kcl.mde.rinform.ItemDeclaration
   * @generated
   */
  EClass getItemDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.mde.rinform.ItemDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.mde.rinform.ItemDeclaration#getName()
   * @see #getItemDeclaration()
   * @generated
   */
  EAttribute getItemDeclaration_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.ItemDescription <em>Item Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item Description</em>'.
   * @see uk.ac.kcl.mde.rinform.ItemDescription
   * @generated
   */
  EClass getItemDescription();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.mde.rinform.ItemDescription#getItemDescription <em>Item Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Item Description</em>'.
   * @see uk.ac.kcl.mde.rinform.ItemDescription#getItemDescription()
   * @see #getItemDescription()
   * @generated
   */
  EAttribute getItemDescription_ItemDescription();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.ItemDescription#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Item</em>'.
   * @see uk.ac.kcl.mde.rinform.ItemDescription#getItem()
   * @see #getItemDescription()
   * @generated
   */
  EReference getItemDescription_Item();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.CharacterDeclaration <em>Character Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Character Declaration</em>'.
   * @see uk.ac.kcl.mde.rinform.CharacterDeclaration
   * @generated
   */
  EClass getCharacterDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.mde.rinform.CharacterDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.mde.rinform.CharacterDeclaration#getName()
   * @see #getCharacterDeclaration()
   * @generated
   */
  EAttribute getCharacterDeclaration_Name();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.CharacterDeclaration#getRoom <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Room</em>'.
   * @see uk.ac.kcl.mde.rinform.CharacterDeclaration#getRoom()
   * @see #getCharacterDeclaration()
   * @generated
   */
  EReference getCharacterDeclaration_Room();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.CharacterDescription <em>Character Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Character Description</em>'.
   * @see uk.ac.kcl.mde.rinform.CharacterDescription
   * @generated
   */
  EClass getCharacterDescription();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.mde.rinform.CharacterDescription#getPersonDescription <em>Person Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Person Description</em>'.
   * @see uk.ac.kcl.mde.rinform.CharacterDescription#getPersonDescription()
   * @see #getCharacterDescription()
   * @generated
   */
  EAttribute getCharacterDescription_PersonDescription();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.CharacterDescription#getPerson <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Person</em>'.
   * @see uk.ac.kcl.mde.rinform.CharacterDescription#getPerson()
   * @see #getCharacterDescription()
   * @generated
   */
  EReference getCharacterDescription_Person();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.DirectionStatement <em>Direction Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Direction Statement</em>'.
   * @see uk.ac.kcl.mde.rinform.DirectionStatement
   * @generated
   */
  EClass getDirectionStatement();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.DirectionStatement#getRoom1 <em>Room1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Room1</em>'.
   * @see uk.ac.kcl.mde.rinform.DirectionStatement#getRoom1()
   * @see #getDirectionStatement()
   * @generated
   */
  EReference getDirectionStatement_Room1();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.mde.rinform.DirectionStatement#getDirection <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Direction</em>'.
   * @see uk.ac.kcl.mde.rinform.DirectionStatement#getDirection()
   * @see #getDirectionStatement()
   * @generated
   */
  EAttribute getDirectionStatement_Direction();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.mde.rinform.DirectionStatement#getRoom2 <em>Room2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Room2</em>'.
   * @see uk.ac.kcl.mde.rinform.DirectionStatement#getRoom2()
   * @see #getDirectionStatement()
   * @generated
   */
  EReference getDirectionStatement_Room2();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.mde.rinform.Words <em>Words</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Words</em>'.
   * @see uk.ac.kcl.mde.rinform.Words
   * @generated
   */
  EClass getWords();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.mde.rinform.Words#getWords <em>Words</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Words</em>'.
   * @see uk.ac.kcl.mde.rinform.Words#getWords()
   * @see #getWords()
   * @generated
   */
  EAttribute getWords_Words();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.mde.rinform.Direction <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Direction</em>'.
   * @see uk.ac.kcl.mde.rinform.Direction
   * @generated
   */
  EEnum getDirection();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RinformFactory getRinformFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.ReverseInformProgramImpl <em>Reverse Inform Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.ReverseInformProgramImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getReverseInformProgram()
     * @generated
     */
    EClass REVERSE_INFORM_PROGRAM = eINSTANCE.getReverseInformProgram();

    /**
     * The meta object literal for the '<em><b>Sentences</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REVERSE_INFORM_PROGRAM__SENTENCES = eINSTANCE.getReverseInformProgram_Sentences();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.SentencePartImpl <em>Sentence Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.SentencePartImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getSentencePart()
     * @generated
     */
    EClass SENTENCE_PART = eINSTANCE.getSentencePart();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.RoomDeclarationImpl <em>Room Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.RoomDeclarationImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getRoomDeclaration()
     * @generated
     */
    EClass ROOM_DECLARATION = eINSTANCE.getRoomDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM_DECLARATION__NAME = eINSTANCE.getRoomDeclaration_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.RoomAliasImpl <em>Room Alias</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.RoomAliasImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getRoomAlias()
     * @generated
     */
    EClass ROOM_ALIAS = eINSTANCE.getRoomAlias();

    /**
     * The meta object literal for the '<em><b>Room</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM_ALIAS__ROOM = eINSTANCE.getRoomAlias_Room();

    /**
     * The meta object literal for the '<em><b>Aliases</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM_ALIAS__ALIASES = eINSTANCE.getRoomAlias_Aliases();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.RoomDescriptionImpl <em>Room Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.RoomDescriptionImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getRoomDescription()
     * @generated
     */
    EClass ROOM_DESCRIPTION = eINSTANCE.getRoomDescription();

    /**
     * The meta object literal for the '<em><b>Room Description</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM_DESCRIPTION__ROOM_DESCRIPTION = eINSTANCE.getRoomDescription_RoomDescription();

    /**
     * The meta object literal for the '<em><b>Room</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM_DESCRIPTION__ROOM = eINSTANCE.getRoomDescription_Room();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.ContainerDeclarationImpl <em>Container Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.ContainerDeclarationImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getContainerDeclaration()
     * @generated
     */
    EClass CONTAINER_DECLARATION = eINSTANCE.getContainerDeclaration();

    /**
     * The meta object literal for the '<em><b>Room</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER_DECLARATION__ROOM = eINSTANCE.getContainerDeclaration_Room();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.ItemInRoomDeclarationImpl <em>Item In Room Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.ItemInRoomDeclarationImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getItemInRoomDeclaration()
     * @generated
     */
    EClass ITEM_IN_ROOM_DECLARATION = eINSTANCE.getItemInRoomDeclaration();

    /**
     * The meta object literal for the '<em><b>Room</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITEM_IN_ROOM_DECLARATION__ROOM = eINSTANCE.getItemInRoomDeclaration_Room();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.ItemInContainerDeclarationImpl <em>Item In Container Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.ItemInContainerDeclarationImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getItemInContainerDeclaration()
     * @generated
     */
    EClass ITEM_IN_CONTAINER_DECLARATION = eINSTANCE.getItemInContainerDeclaration();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITEM_IN_CONTAINER_DECLARATION__CONTAINER = eINSTANCE.getItemInContainerDeclaration_Container();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.ItemDeclarationImpl <em>Item Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.ItemDeclarationImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getItemDeclaration()
     * @generated
     */
    EClass ITEM_DECLARATION = eINSTANCE.getItemDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM_DECLARATION__NAME = eINSTANCE.getItemDeclaration_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.ItemDescriptionImpl <em>Item Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.ItemDescriptionImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getItemDescription()
     * @generated
     */
    EClass ITEM_DESCRIPTION = eINSTANCE.getItemDescription();

    /**
     * The meta object literal for the '<em><b>Item Description</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM_DESCRIPTION__ITEM_DESCRIPTION = eINSTANCE.getItemDescription_ItemDescription();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITEM_DESCRIPTION__ITEM = eINSTANCE.getItemDescription_Item();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.CharacterDeclarationImpl <em>Character Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.CharacterDeclarationImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getCharacterDeclaration()
     * @generated
     */
    EClass CHARACTER_DECLARATION = eINSTANCE.getCharacterDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTER_DECLARATION__NAME = eINSTANCE.getCharacterDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Room</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHARACTER_DECLARATION__ROOM = eINSTANCE.getCharacterDeclaration_Room();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.CharacterDescriptionImpl <em>Character Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.CharacterDescriptionImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getCharacterDescription()
     * @generated
     */
    EClass CHARACTER_DESCRIPTION = eINSTANCE.getCharacterDescription();

    /**
     * The meta object literal for the '<em><b>Person Description</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTER_DESCRIPTION__PERSON_DESCRIPTION = eINSTANCE.getCharacterDescription_PersonDescription();

    /**
     * The meta object literal for the '<em><b>Person</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHARACTER_DESCRIPTION__PERSON = eINSTANCE.getCharacterDescription_Person();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.DirectionStatementImpl <em>Direction Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.DirectionStatementImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getDirectionStatement()
     * @generated
     */
    EClass DIRECTION_STATEMENT = eINSTANCE.getDirectionStatement();

    /**
     * The meta object literal for the '<em><b>Room1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTION_STATEMENT__ROOM1 = eINSTANCE.getDirectionStatement_Room1();

    /**
     * The meta object literal for the '<em><b>Direction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTION_STATEMENT__DIRECTION = eINSTANCE.getDirectionStatement_Direction();

    /**
     * The meta object literal for the '<em><b>Room2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTION_STATEMENT__ROOM2 = eINSTANCE.getDirectionStatement_Room2();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.impl.WordsImpl <em>Words</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.impl.WordsImpl
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getWords()
     * @generated
     */
    EClass WORDS = eINSTANCE.getWords();

    /**
     * The meta object literal for the '<em><b>Words</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORDS__WORDS = eINSTANCE.getWords_Words();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.mde.rinform.Direction <em>Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.mde.rinform.Direction
     * @see uk.ac.kcl.mde.rinform.impl.RinformPackageImpl#getDirection()
     * @generated
     */
    EEnum DIRECTION = eINSTANCE.getDirection();

  }

} //RinformPackage
