/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.rinform;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sentence Part</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.mde.rinform.RinformPackage#getSentencePart()
 * @model
 * @generated
 */
public interface SentencePart extends EObject
{
} // SentencePart
