/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde;

import uk.ac.kcl.mde.AbstractRinformRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RinformRuntimeModule extends AbstractRinformRuntimeModule {
}
