/*
 * generated by Xtext 2.11.0
 */
package uk.ac.kcl.mde.rinform.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uk.ac.kcl.mde.rinform.ui.internal.RinformActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RInformExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RinformActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RinformActivator.getInstance().getInjector(RinformActivator.UK_AC_KCL_MDE_RINFORM_RINFORM);
	}
	
}
