/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RinformStandaloneSetup extends RinformStandaloneSetupGenerated {

	def static void doSetup() {
		new RinformStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
