/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.rinform.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import uk.ac.kcl.mde.rinform.CharacterDeclaration;
import uk.ac.kcl.mde.rinform.CharacterDescription;
import uk.ac.kcl.mde.rinform.RinformPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Character Description</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mde.rinform.impl.CharacterDescriptionImpl#getPersonDescription <em>Person Description</em>}</li>
 *   <li>{@link uk.ac.kcl.mde.rinform.impl.CharacterDescriptionImpl#getPerson <em>Person</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CharacterDescriptionImpl extends SentencePartImpl implements CharacterDescription
{
  /**
   * The cached value of the '{@link #getPersonDescription() <em>Person Description</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPersonDescription()
   * @generated
   * @ordered
   */
  protected EList<String> personDescription;

  /**
   * The cached value of the '{@link #getPerson() <em>Person</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPerson()
   * @generated
   * @ordered
   */
  protected CharacterDeclaration person;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CharacterDescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RinformPackage.Literals.CHARACTER_DESCRIPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getPersonDescription()
  {
    if (personDescription == null)
    {
      personDescription = new EDataTypeEList<String>(String.class, this, RinformPackage.CHARACTER_DESCRIPTION__PERSON_DESCRIPTION);
    }
    return personDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CharacterDeclaration getPerson()
  {
    if (person != null && person.eIsProxy())
    {
      InternalEObject oldPerson = (InternalEObject)person;
      person = (CharacterDeclaration)eResolveProxy(oldPerson);
      if (person != oldPerson)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RinformPackage.CHARACTER_DESCRIPTION__PERSON, oldPerson, person));
      }
    }
    return person;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CharacterDeclaration basicGetPerson()
  {
    return person;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPerson(CharacterDeclaration newPerson)
  {
    CharacterDeclaration oldPerson = person;
    person = newPerson;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RinformPackage.CHARACTER_DESCRIPTION__PERSON, oldPerson, person));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RinformPackage.CHARACTER_DESCRIPTION__PERSON_DESCRIPTION:
        return getPersonDescription();
      case RinformPackage.CHARACTER_DESCRIPTION__PERSON:
        if (resolve) return getPerson();
        return basicGetPerson();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RinformPackage.CHARACTER_DESCRIPTION__PERSON_DESCRIPTION:
        getPersonDescription().clear();
        getPersonDescription().addAll((Collection<? extends String>)newValue);
        return;
      case RinformPackage.CHARACTER_DESCRIPTION__PERSON:
        setPerson((CharacterDeclaration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RinformPackage.CHARACTER_DESCRIPTION__PERSON_DESCRIPTION:
        getPersonDescription().clear();
        return;
      case RinformPackage.CHARACTER_DESCRIPTION__PERSON:
        setPerson((CharacterDeclaration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RinformPackage.CHARACTER_DESCRIPTION__PERSON_DESCRIPTION:
        return personDescription != null && !personDescription.isEmpty();
      case RinformPackage.CHARACTER_DESCRIPTION__PERSON:
        return person != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (personDescription: ");
    result.append(personDescription);
    result.append(')');
    return result.toString();
  }

} //CharacterDescriptionImpl
