/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.rinform.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.mde.rinform.RinformPackage;
import uk.ac.kcl.mde.rinform.SentencePart;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sentence Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SentencePartImpl extends MinimalEObjectImpl.Container implements SentencePart
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SentencePartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RinformPackage.Literals.SENTENCE_PART;
  }

} //SentencePartImpl
