/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.ide;

import uk.ac.kcl.mde.ide.AbstractRinformIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RinformIdeModule extends AbstractRinformIdeModule {
}
