/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.rinform.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import uk.ac.kcl.mde.rinform.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.mde.rinform.RinformPackage
 * @generated
 */
public class RinformAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static RinformPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RinformAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = RinformPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RinformSwitch<Adapter> modelSwitch =
    new RinformSwitch<Adapter>()
    {
      @Override
      public Adapter caseReverseInformProgram(ReverseInformProgram object)
      {
        return createReverseInformProgramAdapter();
      }
      @Override
      public Adapter caseSentencePart(SentencePart object)
      {
        return createSentencePartAdapter();
      }
      @Override
      public Adapter caseRoomDeclaration(RoomDeclaration object)
      {
        return createRoomDeclarationAdapter();
      }
      @Override
      public Adapter caseRoomAlias(RoomAlias object)
      {
        return createRoomAliasAdapter();
      }
      @Override
      public Adapter caseRoomDescription(RoomDescription object)
      {
        return createRoomDescriptionAdapter();
      }
      @Override
      public Adapter caseContainerDeclaration(ContainerDeclaration object)
      {
        return createContainerDeclarationAdapter();
      }
      @Override
      public Adapter caseItemInRoomDeclaration(ItemInRoomDeclaration object)
      {
        return createItemInRoomDeclarationAdapter();
      }
      @Override
      public Adapter caseItemInContainerDeclaration(ItemInContainerDeclaration object)
      {
        return createItemInContainerDeclarationAdapter();
      }
      @Override
      public Adapter caseItemDeclaration(ItemDeclaration object)
      {
        return createItemDeclarationAdapter();
      }
      @Override
      public Adapter caseItemDescription(ItemDescription object)
      {
        return createItemDescriptionAdapter();
      }
      @Override
      public Adapter caseCharacterDeclaration(CharacterDeclaration object)
      {
        return createCharacterDeclarationAdapter();
      }
      @Override
      public Adapter caseCharacterDescription(CharacterDescription object)
      {
        return createCharacterDescriptionAdapter();
      }
      @Override
      public Adapter caseDirectionStatement(DirectionStatement object)
      {
        return createDirectionStatementAdapter();
      }
      @Override
      public Adapter caseWords(Words object)
      {
        return createWordsAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.ReverseInformProgram <em>Reverse Inform Program</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.ReverseInformProgram
   * @generated
   */
  public Adapter createReverseInformProgramAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.SentencePart <em>Sentence Part</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.SentencePart
   * @generated
   */
  public Adapter createSentencePartAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.RoomDeclaration <em>Room Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.RoomDeclaration
   * @generated
   */
  public Adapter createRoomDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.RoomAlias <em>Room Alias</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.RoomAlias
   * @generated
   */
  public Adapter createRoomAliasAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.RoomDescription <em>Room Description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.RoomDescription
   * @generated
   */
  public Adapter createRoomDescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.ContainerDeclaration <em>Container Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.ContainerDeclaration
   * @generated
   */
  public Adapter createContainerDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.ItemInRoomDeclaration <em>Item In Room Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.ItemInRoomDeclaration
   * @generated
   */
  public Adapter createItemInRoomDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.ItemInContainerDeclaration <em>Item In Container Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.ItemInContainerDeclaration
   * @generated
   */
  public Adapter createItemInContainerDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.ItemDeclaration <em>Item Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.ItemDeclaration
   * @generated
   */
  public Adapter createItemDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.ItemDescription <em>Item Description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.ItemDescription
   * @generated
   */
  public Adapter createItemDescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.CharacterDeclaration <em>Character Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.CharacterDeclaration
   * @generated
   */
  public Adapter createCharacterDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.CharacterDescription <em>Character Description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.CharacterDescription
   * @generated
   */
  public Adapter createCharacterDescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.DirectionStatement <em>Direction Statement</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.DirectionStatement
   * @generated
   */
  public Adapter createDirectionStatementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link uk.ac.kcl.mde.rinform.Words <em>Words</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see uk.ac.kcl.mde.rinform.Words
   * @generated
   */
  public Adapter createWordsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //RinformAdapterFactory
