/*
 * generated by Xtext 2.11.0
 */
package uk.ac.kcl.mde.rinform.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRInformScopeProvider extends DelegatingScopeProvider {
}
