/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.mde.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.mde.RinformRuntimeModule;
import uk.ac.kcl.mde.RinformStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RinformIdeSetup extends RinformStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RinformRuntimeModule(), new RinformIdeModule()));
	}
	
}
