/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.mde.rinform.ui.internal.RinformActivator;

public class RinformUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RinformActivator.getInstance().getInjector("uk.ac.kcl.mde.Rinform");
	}

}
