/**
 * generated by Xtext 2.11.0
 */
package uk.ac.kcl.mde.rinform.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uk.ac.kcl.mde.rinform.ui.AbstractRInformUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RInformUiModule extends AbstractRInformUiModule {
  public RInformUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
